### ISSUE TITLE
Completely broken with latest AUTOMATIC1111 commit

### ISSUE THREAD

**Issue by mlmcgoogan** [amotile/stable-diffusion-backend#1]
Hey amotile, appreciate everything you're doing here!

Did a little looking, appears to be due to Line 57 in `/src/process/implementations/automatic1111.ts`

Some change in auto1111's config for components and plural **seeds** doesn't appear to be present anymore? Haven't worked out what the new approach is supposed to be yet but wanted to raise the flag on it because it's completely broken as of now (even if you try to work around not having **seeds**, requests fail).

Error on `npm start` for backend.

`Error: No img2img function found
    at /home/subpanic/repo/stable-diffusion-backend/src/process/implementations/automatic1111.ts:69:15
    at step (/home/subpanic/repo/stable-diffusion-backend/src/process/implementations/automatic1111.ts:33:23)
    at Object.next (/home/subpanic/repo/stable-diffusion-backend/src/process/implementations/automatic1111.ts:14:53)
    at fulfilled (/home/subpanic/repo/stable-diffusion-backend/src/process/implementations/automatic1111.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`

**Comment by amotile** [comment]
It seems to work for me now with the latest. Can you confirm it still does not work for you? It seems they changed something about seeds in the repo again.

**Comment by mlmcgoogan** [comment]
Pulled latest, so latest auto111 + latest SD studio backend + latest SD studio
auto1111 (35c45df28b303a05d56a13cb56d4046f08cf8c25)
sd studio backend (c6b11731a8a76b6470e89c4c8a2c931672ec125b)
sd studio (8c1bd17080cd40cf42b66d11f470f260e2982ce5)

Looking at the config SD Studio Backend is pulling from auto1111 via `http://localhost:7860/config` - there's just no components coming back with a `seeds` label anymore. Not sure if there are other variables at play that could impact this. Tried launching auto1111 with different args/no args but still not seeing `seeds` anymore.

**Comment by mlmcgoogan** [comment]
And I'm an idiot. When I was messing around on the AUTO1111 side I accidentally wiped the 2 required scripts for SD Studio. So it was just the scripts missing. Things all working now. Sorry about that!!
