### ISSUE TITLE
syntax conflicting with the sd-dynamic-prompts

### ISSUE THREAD

**Issue by Extraltodeus** [amotile/stable-diffusion-backend#4]
I'm talking about that wildcard extension : https://github.com/adieyal/sd-dynamic-prompts

Unfortunately the {word|word} syntax is already used. Would there be any possibility to use an alternative one?

Like {word#word} maybe?

**Comment by Extraltodeus** [comment]
completely mixed two tabs sorry

**Comment by Extraltodeus** [comment]
Thought I had mixed with another tab but no, this is the right place 😅

I am of course talking about your prompt blending script : https://github.com/amotile/stable-diffusion-backend/blob/master/src/process/implementations/automatic1111_scripts/prompt_blending.py

**Comment by Extraltodeus** [comment]
I made myself a copy and decided to replace the separator by "&" which also makes sense :)
Feel free to close this ticket if you feel like it.

**Comment by SparkyFluffbutt** [comment]
I'm also having this issue, and I have no way of verifying if the change made actually does anything

**Comment by Extraltodeus** [comment]
I'll be honest after some testing using [word1|word2] (which alternates the words in between each step) and this extension it appears that the [|] method works better. The effect of this extension is a very interesting experiment. Yet it seems that the word with the most influence largely wins over the other.

I tried plane with car. The [|] method gave me a fusion in between the two concepts. This extension gave me sport cars. So somehow, while I praise the interest of this experimental script and thanks @amotile, it does not seem to give significant results. At least for me.

**Comment by SparkyFluffbutt** [comment]
Ok, I'm just going to have to open a new issue then since your being satisfied hasn't actually resolved the conflict.
