### ISSUE TITLE
Question about a similar feature in the webui

### ISSUE THREAD

**Issue by PladsElsker** [amotile/stable-diffusion-backend#6]
Hi, I was wondering what the concrete difference between the prompt blending script and the `AND` keyword was in the webui. 

Also, sorry if this is the wrong place to ask! 
I'm just wondering how this script differs from this similar feature in the webui, and I'm not sure where to ask other than in the issues themselves.

**Comment by amotile** [comment]
I think they work differently under the hood so you would get different result.
But for my use it was the possibility to blend between them that was important so you can animate from one to the other.
At the time of creating it, that was not possible with AND.
